name: Midka
version: ${project.version}
main: dev.midka.eka.Eka
api-version: 1.16
authors: [Midka]
description: My first plugin
website: midka.dev

commands:
  launch:
    aliases: lch
  doctor:
    permission: eka.doctor.use
    permission-message: You do not have permission!
    usage: /doctor
    description: Ask's you do you want to be healed

  godboots:
  destinyspear:
    aliases: dspear
  changeteam:
  gamble:
  gmc:
    permission: eka.gamemode.change
    aliases:
      - gms
      - gmsr
      - gma


permissions:
  eka.*:
    default: op
    children:
      eka.gamble.use: true
      eka.doctor.use: true
      eka.gamemode.change: true